### ISSUE TITLE
Scores and ranking position do not change on GermanCredit and COMPAS datasets

### ISSUE THREAD

**Issue by haolun-wu** [MilkaLichtblau/BA_Laura#2]
Hi, when I ran your demo by using FOEIR and FA-IR methods on GermanCredita and COMPAS datasets, I found the "Original score", "learned_scores", and "Ranking score from post-processing" are always the same. Also, the ranking position seems also the same, they do not change. (While I found the algorithms work for the TREC dataset.) May I ask if this is due to some parameter tuning?

The same circumstance occurs in your results provided in the "ranking" file on github. For instance, in GermanCredit sex ranking by using FOEIR, the scores never change:
![image](https://user-images.githubusercontent.com/33157137/105214654-47ff6b00-5b1e-11eb-9a93-ee8e10701daa.png)

**Comment by MilkaLichtblau** [comment]
Haolun,

Can you provide me with the parameters that you chose when running the
system? Also please tell more about the setup, the script you ran and
everything, otherwise I can't help you. Please write your question with the
same standards as for Stackoverflow.

Thank you

**Comment by haolun-wu** [comment]
Hi Meike,

Thanks for the suggestion, actually I directly run "python runBenchmarking.py" by using your GitHub code in my Python 3.7 without changing anything. After running it, I checked the output file in directory __"rankings/FA-IR"__ and __"rankings/FOEIR-..."__, and I found the ___"original score"___, ___"learned score"___, and ___"Ranking score from postprocessing"___ are exactly the same for _GermanCreditSex.csv_ data, for instance. And if you check the file in the same directory on GitHub, you can have the same observation.

Is this information enough? since I did not change anything but directly ran the code. Basically, I hope to get a new ranking by using your project, but from my understanding, if the "learned score" and the "original score" have no difference, then the ranking will also not change. 

Hope you could answer my concern, or tell me if there is anything I need to change in the code.

Best regards,
Haolun

**Comment by eleicha** [comment]
Hey Haolun,

the algorithms you mentioned are postprocessing algorithms. They do not create new scores but rather reorder rankings based on the provided scores by learning to rank algorithms. I enabled the display of three different score types due to the prospect of implementing fair learning to rank algorithms and more postprocessing algorithms that might need these scores in the future, but never did. Also, some utility and fairness measures use these scores to evaluate the produced rankings with respect to certain criteria. 
If the algorithms do not create a new ordering, then with regard to the respective fairness criterion used in this algorithm, the ranking has already been fair. If you want to learn more about the postprocessing algorithms, I would suggest you take a look at the papers they are based upon. The papers are provided on the front page. 
Additionally, only the TREC data set is an actual learning to rank data set. The other data sets have already learned scores, learned externally from some learning to rank algorithm, hence, I do not possess the original score. For implementation purposes, in the display, the original score for those is just a copy of the learned score. If you open the folder, where the data sets are stored, there is a README providing additional information and a link to the sources of the given data sets. 

Hope I could help.

Cheers,
Laura

**Comment by haolun-wu** [comment]
Hi Laura,

Thanks so much. Your answer answered my concern. Thanks, I am new to this field and I will carefully read the related works.

Best regards,
Haolun
